version: '3.8'

services:
  mission:
    build:
      context: ./nodetest
      dockerfile: dockerfile
    container_name: mission
    ports:
      - "3000:3000"
      - "3001:3001"
    env_file:
      - ./nodetest/.env
    restart: always
    volumes:
      - /home/ubuntu/docker/msa_gateway/public/vote_images:/app/public/vote_images
      - /home/ubuntu/docker/msa_gateway/public/mission_images:/app/public/mission_images
      - /home/ubuntu/docker/msa_gateway/public/community_images:/app/public/community_images
      - /home/ubuntu/docker/msa_gateway/public/chat_message_images:/app/public/chat_message_images
