version: "3.8"
services:
  intent:
    build: ./intent_server
    ports:
      - "8002:8002"
    container_name: intent1

  rag_server:
    build: ./rag_server
    ports:
      - "8004:8004"
    container_name: rag_server
