version: '3.8'

services:
  signaling-server:
    build: ./webRTC
    container_name: webrtc-signaling
    ports:
      - "3005:3005"
    volumes:
      - ./webRTC:/app
    working_dir: /app
    restart: unless-stopped

  turn-server:
    image: instrumentisto/coturn
    container_name: coturn
    ports:
      - "15000:15000"
      - "15443:15443"
      - "15000:15000/udp"
      - "15443:15443/udp"
    volumes:
      - ./webRTC/turn/turnserver.conf:/etc/coturn/turnserver.conf
    command: ["-c", "/etc/coturn/turnserver.conf"]
    restart: unless-stopped
