version: '3.8'

services:
  mission:
    build:
      context: ./nodetest
      dockerfile: Dockerfile
    container_name: mission
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always
