version: '3.8'

services:
  mission:
    build:
      context: ./nodetest
      dockerfile: dockerfile
    container_name: mission
    ports:
      - "3000:3000"
      - "3001:3001"
    env_file:
      - ./nodetest/.env
    restart: always
