version: "3.8"
services:
  api_gateway:
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    restart: always
    volumes:
      - /home/ubuntu/docker/nodetest/api_gateway/public/vote_images:/app/public/vote_images
      - /home/ubuntu/docker/nodetest/api_gateway/public/profile_images:/app/public/profile_images
      - /home/ubuntu/docker/nodetest/api_gateway/public/mission_images:/app/public/mission_images
      - /home/ubuntu/docker/nodetest/api_gateway/public/community_images:/app/public/community_images
      - /home/ubuntu/docker/nodetest/api_gateway/public/chat_message_images:/app/public/chat_message_images
    networks:
      - shared-net

networks:
  shared-net:
    external: true