name: capstone_1_project
description: "graduation_project"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  permission_handler: ^11.3.1
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  email_validator: ^3.0.0
  http: ^1.2.2
  url_launcher: ^6.3.1
  shared_preferences: ^2.0.15
  image_picker: ^1.1.2
  provider: ^6.0.5
  socket_io_client: ^3.0.2
  badges: ^3.1.2
  web_socket_channel: ^3.0.1
  path_provider: ^2.0.11
  camera: ^0.11.0
  image_gallery_saver: ^2.0.3
  photo_manager: ^3.6.3
  exif: ^3.3.0
  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.6
  table_calendar: ^3.0.7
  image: ^4.0.15
  flutter_localizations:
    sdk: flutter
  flutter_time_picker_spinner: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/Roboto-Regular.ttf

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
