name: capstone_1_project
description: "graduation_project"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  
  flutter_webrtc: 0.9.40 #WEB RTC
  
  vibration: ^1.7.4
  audioplayers: ^5.2.1
  openid_client: ^0.4.8
  uuid: ^4.3.1
  agora_rtc_engine: ^6.2.5
  permission_handler: ^11.3.1
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  email_validator: ^3.0.0
  http: ^0.13.6
  url_launcher: ^6.3.1
  shared_preferences: ^2.0.15
  image_picker: ^1.1.2
  provider: ^6.0.5
  socket_io_client: ^3.0.2
  badges: ^3.1.2
  web_socket_channel: ^3.0.1
  path_provider: ^2.0.11
  camera: ^0.11.0
  #gallery_saver: ^2.3.0
  photo_manager: ^3.6.3
  exif: ^3.3.0
  dio: ^5.2.0
  flutter_web_auth_2: ^2.0.2
  firebase_core: ^3.13.0
  firebase_auth: ^5.0.0 # 예시로 인증 기능 추가
  cloud_firestore: ^5.0.0
  flutter_local_notifications: 14.1.1
  firebase_messaging: ^15.0.0
  app_links: ^3.1.0
  
  table_calendar: ^3.0.7
  image: ^4.0.17
  flutter_localizations:
    sdk: flutter
  flutter_time_picker_spinner: ^2.0.0
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  jwt_decoder: ^2.0.1
  flutter_launcher_icons: ^0.14.2  # 새로 추가된 부분


flutter:
  uses-material-design: true
  assets:
    - assets/ProfileEX1.jpg
    - assets/ProfileEX2.jpg


