version: 0.0
os: linux

files:
  - source:  /
    destination: /home/ubuntu/nodetest
    fileExistsBehavior: OVERWRITE
    overwrite: true
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: scripts/cleanup.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/stop.sh
      timeout: 60
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: ubuntu